DROP DATABASE IF EXISTS ToDo;
CREATE DATABASE Todo;
USE Todo;

CREATE TABLE USUARIO (
    USER_ID INT NOT NULL AUTO_INCREMENT,
    USER_NOME VARCHAR(255) NOT NULL,
    USER_EMAIL VARCHAR(255) NOT NULL,
    USER_SENHA VARCHAR(255) NOT NULL,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE TAREFAS (
    TAR_ID INT NOT NULL AUTO_INCREMENT,
    TAR_USER_ID INT NOT NULL,
    TAR_TITULO VARCHAR(255) NOT NULL,
    TAR_DESCRICAO VARCHAR(255),
    TAR_STATUS VARCHAR(255) NOT NULL,
    TAR_DATA DATE NOT NULL,
    PRIMARY KEY (TAR_ID),
    FOREIGN KEY (TAR_USER_ID) REFERENCES USUARIO(USER_ID)
);